FROM python:3.8



RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN pip install transformers==4.14.1 \
   datasets \
   sklearn

RUN pip install torch==1.10.1+cpu \
   torchvision==0.11.2+cpu \
   torchaudio==0.10.1+cpu \
   -f https://download.pytorch.org/whl/cpu/torch_stable.html 

RUN pip install black

RUN apt update && \
   apt install -y make