# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: addons.models.MultiLingualBertIntentClassifier
    url: http://model-server:8000/classify
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: AugmentedMemoizationPolicy
    max_history: 20
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 20
    epochs: 200
    constrain_similarities: true
